vidly/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:movie_id>', views.detail, name="detail")
]

vidly/vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path("", views.home),
    path("admin/", admin.site.urls),
    path("movies/", include("movies.urls")),
    path("api/", include(movie_resource.urls)),
    
]

vidly/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = "movies"
        fields = ["id", "title", "release_year", "number_in_stock", "daily_rate", "genre", "date_created"]

vidly/movies/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_reate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=datetime.now)

vidly/api/views.py
from django.shortcuts import render

# Create your views here.

vidly/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render,  get_object_or_404
from .models import Movie

# Create your views here.

def index(request):
    movies = Movie.objects.all()
    title = ".".join([movie.title for movie in movies])
    # return HttpResponse(title)
    return render(request, "movies/index.html", {"movies" : movies})

def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, "movies/detail.html", {"movie": movie})
    # Alternatively, you can use the following commented code to handle the case where the movie does not exist:
    # try:
    #     movie = Movie.objects.get(pk=movie_id)
    #     return render(request, "movies/detail.html", {"movie": movie})
    # except Movie.DoesNotExist:
    #     raise Http404("Movie does not exist")

vidly/vidly/views.py
from django.shortcuts import render


def home(request):
    """
    Home view that renders the home page.
    """
    return render(request, 'home.html')

vidly/movies/templates/movies/detail.html
{% extends "base.html" %}


{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Release Year</dt>
        <dd>{{ movie.release_year }}</dd>
        <dt>Number in Stock</dt>
        <dd>{{ movie.number_in_stock }}</dd>
        <dt>Daily Rate</dt>
        <dd>{{ movie.daily_reate }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Date Created</dt>
        <dd>{{ movie.date_created }}</dd>
    </dl>
{% endblock %}

vidly/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stick</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td><a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

vidly/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-text">
          Vidly
        </span>
      </div>
    </nav>
    <main class="container">
      {% block content %}
      {% endblock %}
    </main>
    
  </body>
</html>

vidly/templates/home.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'movies:index' %}" class="btn btn-primary mb-3">Go to Movies</a>
{% endblock %}